name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambiá a master si tu rama principal se llama así

# Permisos necesarios para escribir en GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-node: 20 # Sintonizado con las herramientas de 2026
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # Usa "npm install" si no tenés un package-lock.json estable

      - name: Execute Tests
        run: npm run test -- --passWithNoTests

      - name: Build Project (Build)
        # Inyectamos la variable de entorno directamente en el entorno de Node antes del Build de Vite
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # La carpeta de salida que genera Vite al compilar
          branch: gh-pages # Rama automática donde se guardará el build listo para producción